---
title: "Rivers to points"
author: "Darren Norris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

### Load packages
```{r load-packages}
library(plyr)
library(tidyverse)
library(sf)
library(terra)
library(mapview)
```

### Load data


```{r load-data}
# Use Amapá to check/test
library(geobr)
ap <- read_state(
  code_state="AP",
  year=2020,
  showProgress = FALSE
  )
ap_crop_box <- ext(vect(st_transform(ap, 4326)))
ap_crop_bbox <- st_bbox(st_transform(ap, 4326))

# Free-flowing rivers
ffr_in <- "C:\\Users\\user\\Documents\\Articles\\gis_layers\\hydro_data\\sa_FFR_river_v1\\sa_FFR_river_v1.shp"
ffr <- read_sf(ffr_in) |> 
  filter(RIV_ORD <= 4) 
# Crop to Amapá
ffr_ap_3395 <- ffr |> st_crop(ap_crop_bbox) |> st_transform(3395)

```

## Make points

Make points for each REACH_ID.
```{r make-points}
# Total river length. 2400.1
total_l <- as.numeric(units::set_units(sum(st_length(ffr_ap_3395)), km))
crop.l <- ffr_ap_3395 |> filter(REACH_ID == 60189196) # 1.5
crop.l <- ffr_ap_3395 |> filter(REACH_ID == 60196707)# short
crop.l <- ffr_ap_3395 |> filter(REACH_ID == 60485447) #long
df_ffr_ap <- ffr_ap_3395 |> data.frame()
# function to make points
river_points <- function(x){
# Points by reach
require(sf)
require(dplyr)
din <- x
crop.l <- st_as_sf(din)
tmpdf <- din |> select(!geometry)
crop.l <- sf::st_cast(sf::st_sfc(sf::st_geometry(crop.l)),"LINESTRING")
crop.l <- sf::st_union(crop.l)
myl <- as.numeric(units::set_units(sum(sf::st_length(crop.l)), km))
crop.l <- sf::st_cast(sf::st_sfc(sf::st_geometry(crop.l)),"LINESTRING")
# Sample line
if(myl < 1){sf.r.segs <- sf::st_line_sample(crop.l, sample = 0) 
} else {sf.r.segs <- sf::st_line_sample(crop.l, density = units::set_units(1, 1/km))}
rm(crop.l)
# Make points
sf.r.segsp <- sf::st_cast(st_sfc(sf::st_geometry(sf.r.segs)),"POINT")
sf.r.segsp <- sf.r.segsp[which(duplicated(st_coordinates(sf.r.segsp ))==FALSE)]
n_rows <- length(sf.r.segsp)
tmpdf <- tmpdf |> dplyr::slice(rep(1:n(), each = n_rows))

# Return sf
tmpsf <- sf::st_sf(tmpdf, geom = sf.r.segsp)
rm(tmpdf)
tmpsf$aid <- row.names(tmpsf)
tmpsf$reach_id_point <- paste(tmpsf$REACH_ID, tmpsf$aid, sep="_")

dfout <- tmpsf |> data.frame() 
rm(tmpsf)
return(dfout)
}

# run function 18:58 approx 1 minute for 2000 km...9:14. 2 min for 4000...
dfres <- ddply(df_ffr_ap, .(REACH_ID), .fun = river_points)
# Remove any duplicate points - e.g. start and end of joining lines.
sf_res <- dfres |> distinct() |> st_as_sf() # 101
sf_res$x <- st_coordinates(sf_res)[, 1]
sf_res$y <- st_coordinates(sf_res)[, 2]
# avoids rounding issues with packages misidentifying duplicate coordinates
sf_res <- sf_res |> 
  mutate(coord_text = paste(floor(x), floor(y), sep="_"))
sf_res$dupe <- duplicated(sf_res$coord_text)
# This remains close to original length. 2318 total = 2400
sf_res <- sf_res |> 
  filter(!dupe, LENGTH_KM >= .8)
mapview::mapview(sf_res)
mapview::mapview(sf_res, zcol = "reach_id_point")
```

### Test extract
Test if gets accessibility. 
```{r test-extract}
# All fine with updated cost-surface process....
access_new <- rast("inst/raster/access_new.tif") # 3395
myext <- ext(vect(sf_res))
access_crop <- crop(access_new, myext)
sr_new <- st_as_sf(extract(access_new, sf_res, bind = TRUE))
sr_new |> data.frame() |> 
  group_by(access_new) |> 
  summarise(river_length = n()) |> 
  ungroup()
# Map to check
mapview::mapview(access_crop) +
mapview::mapview(ffr_ap_3395) + 
  mapview::mapview(sr_new, zcol = "access_new")
```

