---
title: "Test stochastic"
author: "Darren Norris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective
Develop stochastic models to represent populationtrajectories.

## Packages
```{r load-packages, warning=FALSE, message=FALSE}
library(plyr)
library(tidyverse)
library(popdemo)
library(popbio)
```

## Projections
Load functioins.
Load functions.
```{r load-functions}
source('R/pop01_param_poun.R')

```

Each row holds a unique set of parameters 
that reflect diverse recovery (conservation action) and extinction (threat) scenarios.

```{r projection-params}
dt <- pop01_param_poun()
 mydigits <- c(NA, NA, 1, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0 ,0, 2, 2, NA)
slice_head(dt, n = 5)  |> 
  kableExtra::kbl(digits = mydigits) |>
  kableExtra::kable_styling(full_width = F,  latex_options = "hold_position")
```

### Projection models.
```{r projection-models}
# base model that results in population growth with a deterministic model
dt_base <- dt |> filter(type == "base", first_year == 0.2)

 #pop_n <-  100 * c(11.1, 4, 2, 1) 
  stage_names <- c("a1", "a2", "a3", "a4",
                   "b1", "b2", "b3", "b4",
                   "c1", "c2", "c3", "c4",
                   "d1", "d2", "d3", "d4")
  stoch_stage_names <- "b1"
  year_val <- dt_base[ , stoch_stage_names]
  bad_year_thresh <- 0.1
  good_year_thresh <- 0.2
 din <-  dt_base[1 , stage_names] 
 # make vector of stochastic values. Here with 5 matrices. 2 bad 3 good.
 vb1 <- c(0.0001, 0.1, year_val, (year_val + (0.1 * year_val)), 
                                  (year_val + (0.2 * year_val)))
 vb1[vb1 > 1] <- 1
 row_n <- length(vb1)
 dfstoch <- din[rep(seq_len(nrow(din)), row_n), ]
 dfstoch$b1 <- vb1
 
 #list of matrices for projection
 makemat <- function(x){
   vpop <- unlist(x[ , stage_names])
   pop_mat <- matrix(vpop, byrow = TRUE, ncol=4)
   dimnames(pop_mat) <- list(c("a", "b", "c", "d"),
                             c(1,2,3,4))
   mout <- pop_mat
   return(mout)
 }
 
  # Make list 
matlist <- plyr::alply(dfstoch , .margins = 1, .fun = makemat)
pop_mat <- matlist[['3']]
# Deterministic
d1_lambda <- popbio::lambda(pop_mat) # 1.01202
# popdemo::eigs(pop_mat, "lambda") # same
d1_ss <- popdemo::eigs(pop_mat, "ss")
#[1] 0.68656709 0.20232046 0.04642655 0.06468589
fem1 <- 1 / d1_ss[4]
pop_n <-  100 * (fem1 * d1_ss)
ttime <- 100
d1 <- popdemo::project(pop_mat, vector = pop_n, time = ttime)

# How many eggs are needed to make an adult?
# Initial population vector (all eggs)
N0 <- c(1000, 0, 0, 0)
deggs <- popdemo::project(pop_mat, vector = N0, time = ttime)
len <- length(deggs)
Time.intervals <- 0:(len - 1)
ad.fe <- as.integer(trunc(deggs * (popbio::stable.stage(pop_mat)[4])))
data.frame(years = Time.intervals, females = ad.fe)


# Stochastic
ttime <- 100
spr_01 <- popdemo::project(matlist, vector = pop_n, time = ttime)
# list of matrices used for projection years 
spr_01_lmat <- popdemo::mat(spr_01)[popdemo::Aseq(spr_01)] 
# lambda values
spr_01_lambda_vals <- unlist(lapply(spr_01_lmat, popdemo::eigs, what = "lambda"))
spr_01_boot <- Hmisc::smean.cl.boot(spr_01_lambda_vals)
spr_01_boot_mean <- as.numeric(spr_01_boot["Mean"]) # 0.994
spr_01_boot_lcl <- as.numeric(spr_01_boot["Lower"]) # 0.9867
spr_01_boot_ucl <- as.numeric(spr_01_boot["Upper"]) # 1.0007
```

Plot to check
```{r plot-check}

```

Now try 2 in 10.
```{r stochastic-10}
# make vector of stochastic values. Here with 10 matrices. 2 bad 8 good.
 vb1 <- c(0.0001, 0.1, rep(year_val, 8))
 vb1[vb1 > 1] <- 1
 row_n <- length(vb1)
 dfstoch <- din[rep(seq_len(nrow(din)), row_n), ]
 dfstoch$b1 <- vb1
matlist <- plyr::alply(dfstoch , .margins = 1, .fun = makemat) 
spr_01 <- popdemo::project(matlist, vector = pop_n, time = ttime)
# list of matrices used for projection years 
spr_01_lmat <- popdemo::mat(spr_01)[popdemo::Aseq(spr_01)] 
# lambda values
spr_01_lambda_vals <- unlist(lapply(spr_01_lmat, popdemo::eigs, what = "lambda"))
spr_01_boot <- Hmisc::smean.cl.boot(spr_01_lambda_vals)
spr_01_boot_mean <- as.numeric(spr_01_boot["Mean"]) # 1.003
spr_01_boot_lcl <- as.numeric(spr_01_boot["Lower"]) # 0.998
spr_01_boot_ucl <- as.numeric(spr_01_boot["Upper"]) # 1.007

stoch(matlist, c("lambda", "var"), vector = pop_n, Aseq = "unif",
      iterations = 3000, discard = 100)
```

Plot to check.
```{r}
plot(spr_01)
```

Now over different scenarios.
```{r}
# Bad and good years have equal probability
   p2 <- 0.5
   m2 <- matrix(rep(c(p2/2, p2/2, (1-p2)/8, (1-p2)/8, (1-p2)/8, 
                      (1-p2)/8, (1-p2)/8, (1-p2)/8, (1-p2)/8, (1-p2)/8), 10), 10, 10)
   spr_02 <- popdemo::project(matlist, vector = pop_n, Aseq = m2, time = ttime)
   # Bad years occur twice as often as good years.
   p3 <- 0.667
   m3 <- matrix(rep(c(p3/2, p3/2, (1-p3)/8, (1-p3)/8, (1-p3)/8, 
                      (1-p3)/8, (1-p3)/8, (1-p3)/8, (1-p3)/8, (1-p3)/8), 10), 10, 10)
   spr_03 <- popdemo::project(matlist, vector= pop_n, Aseq = m3, time = ttime)
   # Bad years now occur four times as often as good years.
   p4 <- 0.8
   m4 <- matrix(rep(c(p4/2, p4/2, (1-p4)/8, (1-p4)/8, (1-p4)/8, 
                      (1-p4)/8, (1-p4)/8, (1-p4)/8, (1-p4)/8, (1-p4)/8), 10), 10, 10)
   spr_04 <- popdemo::project(matlist, vector= pop_n, Aseq = m4, time = ttime)
```

